In [ ]:
daily_KWh = [400, 800, 400, 500, 600, 550, 600]
total_energy = sum(daily_KWh)
print("Total Energy Used: ", total_energy, "KWH")

Total Energy Used:  3850 KWH

In [ ]:
building_usage = {
    "AIDS": 600,
    "HOSTEL": 850
}
print("HOSTEL used: ", building_usage["HOSTEL"], "KWH")

HOSTEL used:  850 KWH

In [4]:
# program 3: a function to calculate electricity cost
def calculate_bill(kwh, rate_per_unit):
   return kwh * rate_per_unit

today_bill = calculate_bill(600, 3)
print("Today's estimated bill is Rs.", today_bill)

Today's estimated bill is Rs. 1800

In [6]:
# program 4: read a file line by line
with open("campus_energy.csv", "r") as file:
  for line in file.readlines():
     print(line.strip())

date,Buliding,KWR_used,peak hour usage
10/10/2026,CSE,400,200
10/11/2026,HOSTEL,800,333
10/12/2026,CSE,400,200
10/13/2026,ECE,500,210
10/14/2026,CIVIL,600,299
10/15/2026,AIML,550,230
10/16/2026,AIDS,600,299
,,,
,,,
,,,
,,,
,,,

In [9]:
# import the pandas library
import pandas as pd

# load the dataset you created
df = pd.read_csv("campus_energy.csv")

# display the first few rows of the data
print("Here is the raw data:")
display(df.head())

# Group the data to see total usage per building
building_totals = df.groupby("Buliding")["KWR_used"].sum()

print("\nTotal usage per building:")
print(building_totals)

# Generate a statistical summary (average, min, max) of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         date Buliding  KWR_used  peak hour usage
0  10/10/2026      CSE     400.0            200.0
1  10/11/2026   HOSTEL     800.0            333.0
2  10/12/2026      CSE     400.0            200.0
3  10/13/2026      ECE     500.0            210.0
4  10/14/2026    CIVIL     600.0            299.0

Total usage per building:
Buliding
AIDS      600.0
AIML      550.0
CIVIL     600.0
CSE       800.0
ECE       500.0
HOSTEL    800.0
Name: KWR_used, dtype: float64

Statistical Summary:

         KWR_used  peak hour usage
count    7.000000         7.000000
mean   550.000000       253.000000
std    138.443731        55.719536
min    400.000000       200.000000
25%    450.000000       205.000000
50%    550.000000       230.000000
75%    600.000000       299.000000
max    800.000000       333.000000

In [10]:
# create the README.md file and write a message inside it

with open("README.md", "w") as file:
  file.write("# Smart Campus Energy project\n")
  file.write("This repository contains My week 1 hands-on Python and pandas assignments:\n")
  file.write("created by: [Rihan]")

  print("README.md has been successfully created")

README.md has been successfully created

In [ ]:
import matplotlib.pyplot as plt

# A simple bar chart showing energy used by two buildings
buildings